# Generated by Django 4.0.4 on 2022-04-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainArticleApp', '0002_postarticle_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
