# Generated by Django 4.0.4 on 2022-04-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainArticleApp', '0003_registeruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='email',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
