# Generated by Django 4.0.4 on 2022-04-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainArticleApp', '0004_alter_registeruser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='email',
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
