# Generated by Django 4.0.4 on 2022-04-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainArticleApp', '0007_postarticle_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='postArticle',
        ),
    ]
